name: Sync with Upstream

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: galimedo/flurina 
          ref: main
