name: Sync with Upstream

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: galimedo/gh-actions@main
        with:
          target-repo: galimedo/cloud-foundation-fabric
          upstream-repo: GoogleCloudPlatform/cloud-foundation-fabric
          github-token: ${{ secrets.GITHUB_TOKEN }}
