name: Sync with Upstream

on:
  workflow_dispatch:

permissions:
  contents: write     # Changed from 'read' to 'write' to allow pushing
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly pass the token
          fetch-depth: 0                      # Fetch all history
          
      - name: Sync with upstream
        uses: galimedo/gh-actions@main
        with:
          target-repo: galimedo/cloud-foundation-fabric 
          upstream-repo: GoogleCloudPlatform/cloud-foundation-fabric
          github-token: ${{ secrets.GITHUB_TOKEN }}